config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"

  resources :products do
    resources :bookings, only: [:new, :create]
  end




  get "/owned-products", to: "products#index_owned", as: :owned_products

  get "/bookings", to: "bookings#index"
  patch "/bookings/:id", to: "bookings#change_status", as: :booking

  get "/rentals", to: "bookings#rentals_index", as: :rentals

  get "products/users/:id", to: "products#index_for_user", as: :user_products

  get "bookings/:id/ratings/new", to: "ratings#new", as: :new_rating

  post "bookings/:id/ratings", to: "ratings#create", as: :booking_ratings


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  BOOKING_STATUS = %w(Pending Accepted Declined)
  belongs_to :user
  belongs_to :product
  has_one :rating

  validates :status, presence: true, inclusion: { in: BOOKING_STATUS }
  validates :message, presence: true
  validates :start_date, presence: true, comparison: { greater_than_or_equal_to: Date.tomorrow.midnight }
  validates :end_date, presence: true, comparison: { greater_than: :start_date }

  def total_price
    total_price = self.product.price_per_day * ((self.end_date - self.start_date)/86_400).ceil
    final_price = "€#{sprintf('%.2f', total_price)}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  PRODUCT_CATEGORIES = %w(Ski Snowboard Boots Helmet)
  INDEX = ENV["ALGOLIA_INDEX"]

  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  has_many :ratings

  validates :name, presence: true
  validates :category, presence: true, inclusion: { in: PRODUCT_CATEGORIES }
  validates :details, presence: true
  validates :price_per_day, presence: true, comparison: { greater_than: 0 }
  validates :details, presence: true
  validates :photo, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }, allow_nil: true

  include AlgoliaSearch

  algoliasearch index_name: INDEX  do
    add_attribute :image_url do
      photo.url
    end

    add_attribute :address do
      self.user.address.split.last
    end

    add_attribute :latitude do
      self.user.latitude
    end

    add_attribute :longitude do
      self.user.longitude
    end


    searchableAttributes ['name', 'category', 'details', 'address']

    attributesForFaceting ['category', 'address']
    numericAttributesForFiltering ['price_per_day', 'rating']

    customRanking ['desc(rating)']
  end

  def booked_dates
    output = []
    self.bookings.each do |b|
      date = b.start_date
      while date < b.end_date
        output << date
        date = date.next_day
      end
    end
    return output
  end

  def average_rate
    all_ratings = []
    self.bookings.each do |b|
      if b.rating
        all_ratings << b.rating.rating
      end
    end
    if all_ratings.empty?
      return ""
    else
      all_ratings.inject{ |sum, el| sum + el }.to_f / all_ratings.size
    end
    # define method to calculate average_rate from all Bookings of a Product
  end
end

app/models/product_rating.rb
class ProductRating < ApplicationRecord
  belongs_to :booking
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :booking

  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end







end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @product = Product.find(params[:product_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.product = @product
    @booking.status = "Pending"
    if @booking.save
      flash[:success] = "Booking was successfully created"
      redirect_to bookings_path
    else
      flash[:error] = "Something went wrong"
      render "products/show", status: :unprocessable_entity
    end
  end

  def index
    @bookings = Booking.where(user: current_user)
    @rating = Rating.new
  end

  def rentals_index
    @owned_bookings = Booking.joins(:product).where(product: { user: current_user })
  end

  def change_status
    @owned_bookings = Booking.joins(:product).where(product: { user: current_user })
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    @booking.update(booking_params)
    render "/bookings/rentals_index", status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :product_id, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/product_rating_controller.rb
class ProductRatingController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @rating = Rating.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @rating = Rating.new(product_rating_params)
    @rating.user_id = current_user.id
    @rating.product_id = @booking.product_id

    if @rating.save
      redirect_to @booking, notice: "Rating added successfully."
    else
      render :new
    end
  end

    private

  def product_rating_params
    params.require(:rating).permit(:rating, :comment)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.all
    @markers = @products.map do |product|
      {
        userFirstName: product.user.first_name,
        userLastName: product.user.last_name,
        latitude: product.user.latitude,
        longitude: product.user.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {product: product})
      }
    end
  end

  def show
    @booked_dates = @product.booked_dates
    @booking = Booking.new
  end

  def index_owned
    @products = Product.where(user: current_user)
  end

  def index_for_user
    @products = Product.where(user_id: params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to product_path(@product)
    else
      render :new, status: :unprocessable_entity
  end

  def rate
      raise
      @product = Product.find(params[:id])
      rating = params[:rating].to_i
      @product.update(rating: rating)
      puts "you gave a: #{rating} ok we got it"
      redirect_to @product
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :category, :photo, :details, :price_per_day, :rating)
  end

  def set_product
    @product = Product.find(params[:id])
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @rating = Rating.new
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.find(params[:id])
    @rating = Rating.new(rating_params)
    @rating.booking = @booking

    if @rating.save
      redirect_to "/bookings", notice: "Rating added successfully"
    else
      render :new
    end

  end

  private

  def rating_params
    params.require(:rating).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@product, @booking] do |f| %>
  <%= f.input :start_date,
              as: :string,
              input_html: {data: {controller: "datepicker", datepicker_booked_value: @product.booked_dates}} %>
  <%= f.input :end_date,
              as: :string,
              input_html: {data: {controller: "datepicker", datepicker_booked_value: @product.booked_dates}} %>
  <%= f.input :message, as: :text %>
  <div class="d-grid mt-4">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/bookings/_form_validation.html.erb
<%= simple_form_for booking, html: { class: "no-bs-validation row row-cols-auto align-items-center" } do |f| %>
  <%= f.input :status,
              label: false,
              include_blank: false,
              wrapper_html: { class: "mb-auto" },
              collection: Booking::BOOKING_STATUS %>
  <%= f.button :submit, value: "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/bookings/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h2 class="mb-4">All my bookings</h2>
    <%= link_to "Back to products", products_path %>
  </div>
  <% if @bookings.length >= 1 %>
    <% @bookings.each do |b| %>
      <div class="booking-line row">
        <div class="col-1">
          <%= cl_image_tag(b.product.photo.key,
                            :background=>"#F4F4F4",
                            width: 60,
                            height: 60,
                            crop: :fill) %>
        </div>
        <div class="col-1">
          <%= b.product.name %>
        </div>
        <div class="col-1">
          <span class="category-tag"><%= b.product.category %></span>
        </div>
        <div class="col-2">
          <%= "From #{b.start_date.strftime("%d/%m/%Y")} to #{b.end_date.strftime("%d/%m/%Y")}" %>
        </div>
        <div class="col-2">
          <div class="price-tag" style="font-size:14px">
            Total cost: <%= b.total_price %>
          </div>
        </div>
        <div class="col-2">
          Owner: <%= b.product.user.first_name %> <%= b.product.user.last_name %>
        </div>
        <div class="col-2">
          Address: <%= b.user.address %>
        </div>
        <div class="col-1" data-controller="validate">
          <span data-validate-target="tag" class="status-tag d-none"><%= b.status %></span>
        </div>
        <div class="mt-2">
          <% if b.rating %>
            You rated this booking: <%= b.rating.rating %>
          <% else %>
            <%= link_to "Add a rating", new_rating_path(b) %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div>
      <p>You haven't booked any equipment yet.</p>
    </div>
  <% end %>
</div>

app/views/bookings/rentals_index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h2 class="mb-4">My rentals</h2>
    <%= link_to "Back to products", products_path %>
  </div>
  <div data-controller="validate">
    <% @owned_bookings.each do |b| %>
      <div class="booking-line row">
        <div class="col-1">
          <%= cl_image_tag(b.product.photo.key,
                            :background=>"#F4F4F4",
                            width: 60,
                            height: 60,
                            crop: :fill) %>
        </div>
        <div class="col-1">
          <%= b.product.name %>
        </div>
        <div class="col-1">
          <span class="category-tag"><%= b.product.category %></span>
        </div>
        <div class="col-3">
          <%= "From #{b.start_date.strftime("%d/%m/%Y")} to #{b.end_date.strftime("%d/%m/%Y")}" %>
        </div>
        <div class="col-2">
          <div class="price-tag" style="font-size:14px">Total earnings: <%= b.total_price %>
          </div>
        </div>
        <div class="col-2">
          Requester: <%= b.user.first_name %> <%= b.user.last_name %>
        </div>
        <div class="col-2 d-flex">
          <div>
            <p data-validate-target="tag" class="status-tag d-none mb-0"><%= b.status %></p>
          </div>
          <% if b.status == "Pending" %>
            <div class="d-flex align-items-center">
              <%= button_to booking_path(b),
                                      method: :patch,
                                      class: "border-0 bg-white text-success",
                                      params: { booking: { status: "Accepted" } },
                                      data: { action: "click->validate#acceptBooking"} do %>
                                        <i class="fa-regular fa-circle-check fs-4"></i>
              <% end %>
              <%= button_to booking_path(b),
                                      method: :patch,
                                      class: "border-0 bg-white text-danger",
                                      params: { booking: { status: "Declined" } },
                                      data: {action: "click->validate#declineBooking"} do %>
                                        <i class="fa-solid fa-trash fs-4" data-action="click->validate#declineBooking"></i>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="mt-4">
          <span class="mb-0">
            <i class="fa-solid fa-envelope me-2"></i>
            Message from <%= b.user.first_name%> <%= b.user.last_name %>:
          </span>
          <%= b.message %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/bookings/sales_index.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h2 class="mb-4">My sales portfolio</h2>
    <%= link_to "Back to products", products_path %>
  </div>
  <div data-controller="validate">
    <% @owned_bookings.each do |b| %>
      <div class="booking-line row">
        <div class="col-1">
          <%= cl_image_tag(b.product.photo.key,
                            :background=>"#F4F4F4",
                            width: 60,
                            height: 60,
                            crop: :fill) %>
        </div>
        <div class="col-1">
          <%= b.product.name %>
        </div>
        <div class="col-1">
          <span class="category-tag"><%= b.product.category %></span>
        </div>
        <div class="col-3">
          <%= "From #{b.start_date.strftime("%d/%m/%Y")} to #{b.end_date.strftime("%d/%m/%Y")}" %>
        </div>
        <div class="col-2">
          Total cost: <%= b.total_price %>
        </div>
        <div class="col-2">
          To: <%= b.user.first_name %> <%= b.user.last_name %>
        </div>
        <div class="col-2 d-flex">
          <div>
            <p data-validate-target="tag" class="status-tag d-none mb-0"><%= b.status %></p>
          </div>
          <% if b.status == "Pending" %>
            <div class="d-flex align-items-center">
              <%= button_to booking_path(b),
                                      method: :patch,
                                      class: "border-0 bg-white text-success",
                                      params: { booking: { status: "Accepted" } },
                                      data: { action: "click->validate#acceptBooking"} do %>
                                        <i class="fa-regular fa-circle-check fs-5"></i>
              <% end %>
              <%= button_to booking_path(b),
                                      method: :patch,
                                      class: "border-0 bg-white text-danger",
                                      params: { booking: { status: "Declined" } },
                                      data: {action: "click->validate#declineBooking"} do %>
                                        <i class="fa-solid fa-trash fs-5" data-action="click->validate#declineBooking"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkiRental</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('logo.png') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@8.1.0/themes/satellite-min.css" integrity="sha256-p/rGN4RGy6EDumyxF9t7LKxWGg6/MZfGhJM/asKkqvA=" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <%= javascript_importmap_tags %>


    <%# <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.css@8.1.0/themes/reset-min.css" integrity="sha256-2AeJLzExpZvqLUxMfcs+4DWcMwNfpnjUeAAvEtPr0wU=" crossorigin="anonymous"> %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/algoliasearch@4.22.1/dist/algoliasearch-lite.umd.js" integrity="sha256-pxkGFjfnFWYGOtV9uhCWK/spKiGS0Z7gVDKYm39LyfM=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4.64.2/dist/instantsearch.production.min.js" integrity="sha256-/DLulTBQ8KQ7xGOs8mrQ6FgKsknJpjCGAjFhjfjc8yo=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_info_window.html.erb
<div>
  <div class="fw-bold">
    <%= product.user.first_name %> <%= product.user.last_name %>
  </div>
  <div>
    <%= product.user.address %>
  </div>
  <%= link_to "See all products", user_products_path(product.user) %>
  (<%= product.user.products.size %>)
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-8">
    <div class="container" data-controller="search" data-search-index-value="<%= ENV['ALGOLIA_INDEX'] %>">
      <div class=search-menu>
        <div id="searchbox"></div>
        <div class="search-options">
          <div class="category-picker">
            <div class="category-tag">Choose Category</div>
            <div id="filter-list"></div>
          </div>
          <div class="price-picker">
            <div class="price-tag">Filter by price</div>
            <div id="range-slider"></div>
          </div>
        </div>
      </div>
      <div id="hits"></div>
    </div>
  </div>

  <div class="col-4">
    <div id="map"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

</div>

app/views/products/index_for_user.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <div>
      <h2><%= @products.first.user.first_name %> <%= @products.first.user.last_name %></h2>
      <p><%= @products.first.user.address %></p>
    </div>
    <%= button_to "Back to all products", products_path, class: "btn btn-primary", method: :get %>
  </div>
  <div id="hits">
    <div class="ais-Hits">
      <ol class="ais-Hits-list">
        <% @products.each do |product| %>
          <li class="ais-Hits-item">
            <a class="hit-link" href="/products/<%= product.id %>">
              <div class="hit-image">
                <img height="200" src="<%= product.photo.url %>" alt=""/>
              </div>
              <h3 class="hit-name"><%= product.name %></h3>
              <div class="hit-data">
                <p class="category-tag"><%= product.category %></p>
                <p class="price-tag">€<%= product.price_per_day.to_i %>/day</p>
              </div>
            </a>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/products/index_owned.html.erb
<div class="container">
  <div class="d-flex justify-content-between">
    <h2>All my products</h2>
    <%= button_to "List a product", new_product_path, class: "btn btn-primary", method: :get %>
  </div>
    <div id="hits">
      <div class="ais-Hits">
        <ol class="ais-Hits-list">
          <% @products.each do |product| %>
            <li class="ais-Hits-item">
              <a class="hit-link" href="/products/<%= product.id %>">
                <div class="hit-image">
                  <img height="200" src="<%= product.photo.url %>" alt=""/>
                </div>
                <h3 class="hit-name"><%= product.name %></h3>
                <div class="hit-data">
                  <p class="category-tag"><%= product.category %></p>
                  <p class="price-tag">€<%= product.price_per_day.to_i %>/day</p>
                </div>
              </a>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div class="col-6">
    <div class="container" style="max-width: 80%">
      <h2 class="mb-4">Add a new product to rent</h2>
      <%= simple_form_for @product do |f| %>
        <%= f.input :category, :collection => Product::PRODUCT_CATEGORIES %>
        <%= f.input :name %>
        <%= f.input :details %>
        <%= f.input :price_per_day %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, "Add product", class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="col-6">
    <%= image_tag "yellow-ski-drawing.jpg", alt: "yellow ski", width: "100%", height: "550px" %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1 class="mb-3"><%= @product.name %></h1>
  <div class="row gx-5 mb-4">
    <div class="col-4">
      <span class="category-tag mb-3"><%= @product.category %></span>
      <%= cl_image_tag(@product.photo.key,
                        :background=>"#F4F4F4",
                        width: 350,
                        crop: :fill) %>
      <div class="mt-3">
        <% unless @product.average_rate == "" %>
          <span class="fs-5">Average rating: </span>
          <span class="rating-tag"><%= @product.average_rate %></span>
        <% else %>
          <span class="fs-5">No ratings for this product yet.</span>
        <% end  %>
      </div>
    </div>
    <div class="col-4 product-show-details">
      <div class="product-show-details-top">
        <span class="fs-5 fw-bold mb-3">Description</span>
        <p><%= @product.details %></p>
      </div>
      <div class="product-show-details-bottom">
        <div class="divider"></div>
        <span class="fs-5 fw-bold mb-3">Owner</span>
        <p><%= @product.user.first_name %> <%= @product.user.last_name %> - <%= link_to " all products", user_products_path(@product.user) %></p>
        <div class="divider"></div>
        <span class="fs-5 fw-bold mb-3">Address</span>
        <p><%= @product.user.address %></p>
      </div>
    </div>
    <div class="col-4 booking-card">
      <h2 class="mb-3">Book this product</h2>
      <p><strong class="fs-4">€<%= @product.price_per_day.round %></strong>/day</p>
      <%= render "bookings/form" %>
    </div>
  </div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/ratings/_form.html.erb
<%= simple_form_for [@booking, @rating] do |f| %>
  <%= f.input :rating, :collection => [1,2,3,4,5] %>
  <%= f.input :comment, as: :text, :input_html => {:rows => 10}%>
  <div class="d-grid mt-4">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/ratings/new.html.erb
<div class="row">
  <div class="col-6">
    <div class="container" style="max-width: 80%">
      <h2 class="mb-4">Give a rating to your booking</h2>
      <%= render "ratings/form" %>
    </div>
  </div>
  <div class="col-6">
    <%= image_tag "yellow-ski-drawing.jpg", alt: "yellow ski", width: "100%", height: "550px" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-ski-rental navbar-brand navbar-text bg-primary d-flex">
  <div class="container-fluid" >
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item active m-3">
            <%= button_to "See my bookings", bookings_path, class: "btn btn-secondary", method: :get %>
          </li>
          <li>
            <p class="user-name"><%= "#{current_user.first_name} #{current_user.last_name}" %></p>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "profile.png", class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My products", owned_products_path, class: "dropdown-item" %>
              <%= link_to "My rentals", rentals_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item logout" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>